spring:
  application:
    name: PACKAGE-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: true
  instance:
    hostname: localhost

server:
  port: 8082
